### ISSUE TITLE
Submit multiple task as byte[]

### ISSUE THREAD

**Issue by landdragon** [aneoconsulting/ArmoniK.Extensions.Csharp#72]
https://github.com/aneoconsulting/ArmoniK.Extensions.Csharp/blob/9938d46d818aa690c23549aa618ef79700da25d6/UnifiedApi/Client/Services/Submitter/Service.cs#L549

in this method we should return all the results not only one.

**Comment by ddubuc** [comment]
Good point. It will be fixed in the next release
